{% set name = "jinxed" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc523c74fe676c99ccc69c68c2dcd7d4d2d7b2541f6dbef74ef211aedd8ad0d3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ansicon  # [win]
    - python

test:
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jinxed/
  summary: Jinxed Terminal Library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
